    Traceback (most recent call last):
    File "/usr/local/python/3.12.1/lib/python3.12/site-packages/google/api_core/grpc_helpers.py", line 170, in error_remapped_callable
        return _StreamingResponseIterator(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/local/python/3.12.1/lib/python3.12/site-packages/google/api_core/grpc_helpers.py", line 92, in __init__
        self._stored_first_result = next(self._wrapped)
                                    ^^^^^^^^^^^^^^^^^^^
    File "/usr/local/python/3.12.1/lib/python3.12/site-packages/grpc/_channel.py", line 543, in __next__
        return self._next()
            ^^^^^^^^^^^^
    File "/usr/local/python/3.12.1/lib/python3.12/site-packages/grpc/_channel.py", line 969, in _next
        raise self
    grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
        status = StatusCode.UNAVAILABLE
        details = "Getting metadata from plugin failed with error: 'str' object has no attribute 'before_request'"
        debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"Getting metadata from plugin failed with error: \'str\' object has no attribute \'before_request\'", grpc_status:14, created_time:"2025-03-22T19:16:21.344865657+00:00"}"
    >

    The above exception was the direct cause of the following exception:

    Traceback (most recent call last):
    File "/workspaces/TidalHack/main.py", line 38, in <module>
        sample_compute_routes()
    File "/workspaces/TidalHack/main.py", line 32, in sample_compute_routes
        stream = maps_client.compute_route_matrix(request=request)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/local/python/3.12.1/lib/python3.12/site-packages/google/maps/routing_v2/services/routes/client.py", line 909, in compute_route_matrix
        response = rpc(
                ^^^^
    File "/usr/local/python/3.12.1/lib/python3.12/site-packages/google/api_core/gapic_v1/method.py", line 131, in __call__
        return wrapped_func(*args, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/local/python/3.12.1/lib/python3.12/site-packages/google/api_core/grpc_helpers.py", line 174, in error_remapped_callable
        raise exceptions.from_grpc_error(exc) from exc
    google.api_core.exceptions.ServiceUnavailable: 503 Getting metadata from plugin failed with error: 'str' object has no attribute 'before_request'
